#!/usr/bin/docker build -t meqaris-db -f Dockerfile-meqaris-db .
#
# Meqaris - Docker database container descriptor
#
# Copyright (C) 2023-2025 Bogdan 'bogdro' Drozdowski, bogdro (at) users . sourceforge . net
#
# This file is part of Meqaris (Meeting Equipment and Room Invitation System),
#  software that allows booking meeting rooms and other resources using
#  e-mail invitations.
# Meqaris homepage: https://meqaris.sourceforge.io/
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# https://docs.docker.com/engine/reference/builder/

# https://hub.docker.com/_/postgres
FROM postgres:17

######################################################################
# NOTE: for professional use, you MUST add a permanent storage
######################################################################

RUN mkdir /docker-entrypoint-initdb.d || true
COPY docker/docker-db-create.sh /docker-entrypoint-initdb.d/
RUN chmod a+rx /docker-entrypoint-initdb.d/docker-db-create.sh
USER postgres

EXPOSE 5432
