#!/usr/bin/docker build -t meqaris-db -f Dockerfile-meqaris-db .
# https://docs.docker.com/engine/reference/builder/

# https://hub.docker.com/_/postgres
FROM postgres:latest

######################################################################
# NOTE: for professional use, you MUST add a permanent storage
######################################################################

RUN mkdir /docker-entrypoint-initdb.d || true
COPY docker/docker-db-create.sh /docker-entrypoint-initdb.d/
RUN chmod a+rx /docker-entrypoint-initdb.d/docker-db-create.sh

EXPOSE 5432
